<a href="https://colab.research.google.com/github/Yunho-seo/education_center6/blob/main/01_01_tf1_x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# %tensorflow_version 1.x  # 지원 안됨

import tensorflow as tf
print(tf.__version__)
from tensorflow import keras
print(keras.__version__)

2.12.0
2.12.0


In [2]:
tf.test.gpu_device_name()  # /device:GPU:0 => 런타임 유형 변경

'/device:GPU:0'

In [3]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()  # Tesla T4

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 8673990797990230456
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 14328594432
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 173968837051834712
 physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"
 xla_global_id: 416903419]

In [4]:
268435456 / 1024 / 1024 / 1024  # 0.25 (CPU 메모리)

0.25

In [5]:
14328594432 / 1024 / 1024 / 1024  # 13.34 (GPU 메모리)

13.34454345703125

In [6]:
x = [[2.]]
print(type(x))  # list
m = tf.matmul(x, x)  # matmul() : 행렬곱 연산
print(type(m))  # EagerTensor / 2.0부터는 eager mode / 이전에는 graph mode
# pytorch / tensorflow 동시에 사용한다.
# pytorch : tensorflow의 2.x 형식하고 동일하다. (프로그래밍하기가 편리함) : openAPI가 pytorch를 사용한다.
# YOLOv4까지는 tensorflow로 망을 구성하였다. YOLOv5부터는 pytorch를 사용한다.
# tensorflow 2.x 버전부터 pytorch하고 같은 형식으로 변경됨. (keras를 이용하여)
print('hello. {}'.format(m))

<class 'list'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
hello. [[4.]]


In [7]:
# tensorflow에서도 브로드캐스팅(broadcasting)이 가능하다.
# tensor (3차원 이상의 행렬 데이터) + flow => graph(그래프) 망
a = tf.constant([[1, 2], [3, 4]])
print(a)
b = a + tf.constant([1])  # broadcasting되고 있다.
print(b)
print(type(b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
print(a * b)  # [[1, 2], [3, 4]]에 b인 [[2, 3], [4, 5]]를 곱한 값 
print(a + b)  # [[1, 2], [3, 4]]에 b인 [[2, 3], [4, 5]]를 더한 값 

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 5]
 [7 9]], shape=(2, 2), dtype=int32)


In [10]:
import numpy as np
c = np.multiply(a, b)
print(c)
print(type(c))  # ndarray

[[ 2  6]
 [12 20]]
<class 'numpy.ndarray'>


In [13]:
# tf1.x 버전에서 작동하는 방식 (constant, variables, placeholder)
with tf.compat.v1.Session() as sess:  # session : 원래는 네트워크에서 사용하는 단어 (GPU 네트워크로 연결)
  x = tf.compat.v1.placeholder(tf.float32)  # 데이터를 받는 장소(구역)
  y = tf.square(x)
  z = tf.add(x, y)  # run은, 가장 마지막 node를 호출하면 연결된 모든 노드를 계산하여 결과를 출력한다.
  z0 = sess.run([z], feed_dict = {x: 2.})  # 데이터를 피딩 (feeding)
  z1 = sess.run([z], feed_dict = {x: 2., y: 2.})  # {y: 2.} : y값 제곱을 고정시킴
print('z0 : {},\nz1 : {}'.format(z0, z1))

z0 : [6.0],
z1 : [4.0]


In [14]:
# tensorflow 2.0에서 function base로 전환 : dynamic mode / eager mode
  # numpy, scikits 등 좋은 기능들을 다 취합하였다.
# function base programming으로 전환
import tensorflow as tf
def add(x, y):
  return x + y
@tf.function  # @ 장식자 최적화 : 미리 컴파일한다. (속도 향상)
def compute_z1(x, y):
  return add(x, y)
@tf.function
def compute_z0(x):
  return tf.add(x, tf.square(x))
z0 = compute_z0(2.)
z1 = compute_z1(2., 2.)
print('z0 : {},\nz1 : {}'.format(z0, z1))

z0 : 6.0,
z1 : 4.0
